# testing building with travis
language: objective-c

env:
    matrix:
        - PLATFORM="ios"
        - PLATFORM="android" ANDROID_VERSION="26"

before_install:
    - export ANDROID_HOME=$PWD/android-sdk-macosx
    - export ANDROID_SDK=$ANDROID_HOME
    - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools

install:
    - npm install -g titanium alloy tishadow gulp ticalabash
    - npm install

    - titanium login travisci@appcelerator.com travisci
    - titanium sdk install latest --no-progress-bars

    - gulp 'install:android_sdk'

# before_script:
#     - gulp 'start:emulator'
#     - gulp 'config:tiapp' --test
#
# script:
#     - gulp 'test:calabash'
#     - gulp 'test:jasmine'
